version: 2
jobs:
  build:
    working_directory: ~/wp-e2e-tests
    docker:
      - image: 'circleci/node:8.11.0-browsers'
        environment:
          NODE_ENV: test
          TARGET: IE11
    steps:
      - checkout
      - run: echo 162.222.75.33 ondemand.saucelabs.com | sudo tee -a /etc/hosts
      - run: git submodule init
      - run: git submodule update --remote --force
      - run: cd wp-e2e-tests && git checkout origin/${E2E_BRANCH-master}
      - run: cd wp-e2e-tests && npm install
      - run: cd wp-e2e-tests && npm run decryptconfig && ./run.sh -R -w $RUN_ARGS
      - store_test_results:
          path: wp-e2e-tests/reports/
      - store_artifacts:
          path: wp-e2e-tests/reports/
      - store_artifacts:
          path: wp-e2e-tests/screenshots/
